export default () => {
  return [
    "Did you find what you were looking for?",
    "Mahalo means trash",
    "Aloha for everyone!",
    "Graduation is nigh",
    "add it to the blockchain!!!!! -Raymond Luong",
    "Humuhumunukunukuapua'a is the state fish of Hawaii",
    "Las Vegas is known as the 9th island",
    "Congratulations cohort 21 & 23!",
    "There are no DOM questions",
    "Do you even node js?",
    "Confusion means you're learning!",
    "The only thing stopping you is YOU!",
    "I think therefore I code",
    "Its not a bug, its a feature",
    "The only thing I know is that I know nothing -Socrates",
    "The most disastrous thing that you can ever learn is your first programming language",
    "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
    "Testing leads to failure, and failure leads to understanding",
    "The most valuable thing you can make is a mistake - you can't learn anything from being perfect",
    "Fail Fast; Fail Early",
    "Debugging is like being the detective in a crime movie where you are also the murderer.",
    "First do it, then do it right, then do it better.",
    "If at first you don’t succeed, call it version 1.0.",
    "Weeks of coding can save you hours of planning.",
    "In order to understand recursion, one must first understand recursion",
    "Software being 'Done' is like a lawn being 'Mowed'",
    "One of the best programming skills you can have is knowing when to walk away for awhile"
  ];
};
